[package]
name = "taspromto"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
rumqttc = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dashmap = "4"
json = "0.12"
warp = "0.3"
dotenv = "0.15"
ctrlc = { version = "3", features = ["termination"] }
color-eyre = "0.5"
async-stream = "0.3"
pin-utils = "0.1"
hostname = "0.3"
tokio-stream = "0.1"

[profile.release]
lto = true